const $=s=>document.querySelector(s);let catalog=[],upload=null,libraryUpload=null,selectedPath='';
function show(view){document.querySelectorAll('.view').forEach(v=>v.hidden=true);$(`#${view}View`).hidden=false;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={home:['Workspace','Continue learning'],library:['University library','Choose a lecture'],create:['Mind-map generator','New mind map']};$('#eyebrow').textContent=titles[view][0];$('#pageTitle').textContent=titles[view][1];location.hash=view}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)show(b.dataset.view)});
function renderRecent(){const maps=JSON.parse(localStorage.getItem('lecturemind-recent')||'[]');$('#recentCards').innerHTML=maps.length?maps.map(m=>`<a class="map-card" href="${m.href}"><span class="tag">${m.module}</span><h3>${m.title}</h3><p>${m.semester} · ${m.lecture}</p><footer><span>${m.concepts} concepts</span><b>Open map →</b></footer></a>`).join(''):'<p class="privacy">No generated maps yet.</p>'}
async function loadCatalog(){try{catalog=await fetch('/api/catalog').then(r=>r.json());renderLectures([])}catch(e){toast('Could not read the university library')}}
function renderLectures(rows){$('#lectureList').innerHTML=rows.length?rows.map((x,i)=>`<div class="lecture${x.path===selectedPath?' selected':''}" data-path="${encodeURIComponent(x.path)}"><i>${String(i+1).padStart(2,'0')}</i><span><b>${x.title}</b><small>${x.path}</small></span><button data-path="${encodeURIComponent(x.path)}">Select</button></div>`).join(''):'<p class="privacy">Type a PDF name or path above, or use Browse.</p>'}
function searchFiles(value){const query=value.trim().toLowerCase();libraryUpload=null;selectedPath='';$('#buildSelected').disabled=true;const rows=query?catalog.filter(x=>[x.title,x.filename,x.path,x.module,x.semester].some(v=>String(v||'').toLowerCase().includes(query))).slice(0,50):[];$('#libraryHeading').textContent=query?`${rows.length} matching PDF${rows.length===1?'':'s'}`:'Search for a lecture file';renderLectures(rows)}
$('#fileSearch').oninput=e=>searchFiles(e.target.value);
$('#lectureList').onclick=e=>{const row=e.target.closest('[data-path]');if(!row)return;selectedPath=decodeURIComponent(row.dataset.path);libraryUpload=null;$('#fileSearch').value=selectedPath;$('#libraryHeading').textContent='Selected PDF';$('#buildSelected').disabled=false;renderLectures(catalog.filter(x=>x.path===selectedPath))};
$('#browseLibrary').onclick=()=>{const picker=$('#libraryFile');picker.value='';picker.click()};
$('#libraryFile').onchange=e=>{const file=e.target.files?.[0]||null;if(!file)return;if(file.type&&file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf')){libraryUpload=null;$('#buildSelected').disabled=true;toast('Please choose a PDF file');return}libraryUpload=file;selectedPath='';$('#fileSearch').value=file.name;$('#libraryHeading').textContent='Selected local PDF';$('#buildSelected').disabled=false;$('#lectureList').innerHTML=`<div class="lecture selected"><i>PDF</i><span><b>${file.name}</b><small>Local file selected with Browse</small></span></div>`};
$('#buildSelected').onclick=()=>{if(libraryUpload){const form=new FormData();form.append('pdf',libraryUpload);generate(form,true,libraryUpload.name)}else if(selectedPath)generate({path:selectedPath});else toast('Search for or browse to a PDF first')};
$('#pdfUpload').onchange=e=>{upload=e.target.files[0];$('#uploadName').textContent=upload?.name||'Choose a PDF';$('#uploadBuild').disabled=!upload};$('#uploadBuild').onclick=async()=>{const form=new FormData();form.append('pdf',upload);generate(form,true)};
async function generate(body,isForm=false,uploadName=''){show('library');const name=isForm?(uploadName||upload?.name||'PDF'):body.path.split('/').pop();$('#activityLog').innerHTML=`<div class="job"><b>Analyzing ${name}</b><small>Codex is building the learning dependency graph…</small></div>`;try{const r=await fetch('/api/generate',{method:'POST',headers:isForm?{}:{'Content-Type':'application/json'},body:isForm?body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error);$('#activityLog').innerHTML=`<div class="job"><b>Mind map ready</b><small><a href="viewer.html?id=${data.id}">Open ${data.title} →</a></small></div>`;const recent=JSON.parse(localStorage.getItem('lecturemind-recent')||'[]').filter(x=>x.id!==data.id);recent.unshift({...data,href:`viewer.html?id=${data.id}`,updated:'Just now'});localStorage.setItem('lecturemind-recent',JSON.stringify(recent.slice(0,5)));renderRecent();toast('Mind map generated')}catch(e){$('#activityLog').innerHTML=`<div class="job"><b>Generation stopped</b><small>${e.message}</small></div>`}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)}renderRecent();loadCatalog();show((location.hash||'#home').slice(1));
