const $=s=>document.querySelector(s);let catalog=[],upload=null;
function show(view){document.querySelectorAll('.view').forEach(v=>v.hidden=true);$(`#${view}View`).hidden=false;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={home:['Workspace','Continue learning'],library:['University library','Choose a lecture'],create:['Mind-map generator','New mind map']};$('#eyebrow').textContent=titles[view][0];$('#pageTitle').textContent=titles[view][1];location.hash=view}
document.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)show(b.dataset.view)});
function renderRecent(){const maps=JSON.parse(localStorage.getItem('lecturemind-recent')||'[]');$('#recentCards').innerHTML=maps.length?maps.map(m=>`<a class="map-card" href="${m.href}"><span class="tag">${m.module}</span><h3>${m.title}</h3><p>${m.semester} · ${m.lecture}</p><footer><span>${m.concepts} concepts</span><b>Open map →</b></footer></a>`).join(''):'<p class="privacy">No generated maps yet.</p>'}
async function loadCatalog(){try{catalog=await fetch('/api/catalog').then(r=>r.json());renderSemesters()}catch(e){toast('Could not read the university library')}}
function options(values,placeholder){return `<option value="">${placeholder}</option>`+values.map(v=>`<option>${v}</option>`).join('')}
function renderSemesters(){const semesters=[...new Set(catalog.map(x=>x.semester))];$('#semesterSelect').innerHTML=options(semesters,'Select semester');$('#moduleSelect').innerHTML=options([],'Select module');$('#lectureSelect').innerHTML=options([],'Select lecture');renderLectures([])}
$('#semesterSelect').onchange=e=>{const modules=[...new Set(catalog.filter(x=>x.semester===e.target.value).map(x=>x.module))];$('#moduleSelect').innerHTML=options(modules,'Select module');$('#lectureSelect').innerHTML=options([],'Select lecture');renderLectures([])};
$('#moduleSelect').onchange=e=>{const rows=catalog.filter(x=>x.semester===$('#semesterSelect').value&&x.module===e.target.value);$('#lectureSelect').innerHTML=options(rows.map(x=>x.title),'Select lecture');renderLectures(rows);$('#libraryHeading').textContent=e.target.value||'Select a module'};
$('#lectureSelect').onchange=e=>document.querySelectorAll('.lecture').forEach(x=>x.classList.toggle('selected',x.dataset.title===e.target.value));
function renderLectures(rows){$('#lectureList').innerHTML=rows.length?rows.map((x,i)=>`<div class="lecture" data-title="${x.title}"><i>${String(i+1).padStart(2,'0')}</i><span><b>${x.title}</b><small>${x.filename}</small></span><button data-path="${encodeURIComponent(x.path)}">Transform</button></div>`).join(''):'<p class="privacy">Choose a semester and module to see lecture PDFs.</p>'}
$('#lectureList').onclick=e=>{const b=e.target.closest('[data-path]');if(b)generate({path:decodeURIComponent(b.dataset.path)})};$('#buildSelected').onclick=()=>{const x=catalog.find(x=>x.semester===$('#semesterSelect').value&&x.module===$('#moduleSelect').value&&x.title===$('#lectureSelect').value);if(x)generate({path:x.path});else toast('Select a lecture first')};
$('#pdfUpload').onchange=e=>{upload=e.target.files[0];$('#uploadName').textContent=upload?.name||'Choose a PDF';$('#uploadBuild').disabled=!upload};$('#uploadBuild').onclick=async()=>{const form=new FormData();form.append('pdf',upload);generate(form,true)};
async function generate(body,isForm=false){show('library');const name=isForm?upload.name:body.path.split('/').pop();$('#activityLog').innerHTML=`<div class="job"><b>Analyzing ${name}</b><small>Codex is building the learning dependency graph…</small></div>`;try{const r=await fetch('/api/generate',{method:'POST',headers:isForm?{}:{'Content-Type':'application/json'},body:isForm?body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error);$('#activityLog').innerHTML=`<div class="job"><b>Mind map ready</b><small><a href="viewer.html?id=${data.id}">Open ${data.title} →</a></small></div>`;const recent=JSON.parse(localStorage.getItem('lecturemind-recent')||'[]').filter(x=>x.id!==data.id);recent.unshift({...data,href:`viewer.html?id=${data.id}`,updated:'Just now'});localStorage.setItem('lecturemind-recent',JSON.stringify(recent.slice(0,5)));renderRecent();toast('Mind map generated')}catch(e){$('#activityLog').innerHTML=`<div class="job"><b>Generation stopped</b><small>${e.message}</small></div>`}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)}renderRecent();loadCatalog();show((location.hash||'#home').slice(1));
